apiVersion: v1
kind: Service
metadata:
  name: op-postgresql
  namespace: open-project
  labels:
    name: postgresql
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    name: op-postgresql