kind: PersistentVolume
apiVersion: v1
metadata:
  name: openproject-pv001
  namespace: open-project
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /openproject